const __flash struct mapping our_mappings[] = {
  // KC_1  0  2
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_1 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_1 },
  // KC_2  2  4
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_7 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_7 },
  // KC_3  4  6
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_5 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_5 },
  // KC_4  6  8
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_3 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_3 },
  // KC_5  8  10
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_1 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_1 },
  // KC_6  10  12
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_9 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_9 },
  // KC_7  12  14
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_0 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_0 },
  // KC_8  14  16
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_2 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_2 },
  // KC_9  16  18
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_4 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_4 },
  // KC_0  18  20
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_6 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_6 },
  // KC_MINUS  20  22
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_8 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_8 },
  // KC_EQUAL  22  24
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_GRAVE },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_GRAVE },
  // KC_Q  24  31
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_SCLN },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_SCLN },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_SCLN },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_SCLN },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = MOD4_MASK, .to_modifiers = 0, .to_action = KC_ESCAPE },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_SCLN },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_SCLN },
  // KC_W  31  38
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_COMMA },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_COMMA },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_COMMA },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_COMMA },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_LBRACKET },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_COMMA },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_COMMA },
  // KC_E  38  45
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_DOT },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_DOT },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_DOT },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_DOT },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_RBRACKET },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_DOT },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_DOT },
  // KC_R  45  52
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_P },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_P },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_P },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_P },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_5 },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_P },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_P },
  // KC_T  52  58
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_Y },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_Y },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_Y },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_Y },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_Y },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_Y },
  // KC_Y  58  65
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_F },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_F },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_F },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_F },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_BSLS },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_F },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_F },
  // KC_U  65  73
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_G },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_G },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_G },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_G },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_8 },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_PGUP },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_G },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_G },
  // KC_I  73  81
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_C },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_C },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_C },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_C },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_RBRACKET },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_UP },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_C },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_C },
  // KC_O  81  88
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_R },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_R },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_R },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_R },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_LBRACKET },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_R },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_R },
  // KC_P  88  95
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_L },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_L },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_L },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_L },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_BSLS },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_L },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_L },
  // KC_LBRACKET  95  102
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK|LEFT_SHIFT_MASK, .to_action = KC_GRAVE },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK|RIGHT_SHIFT_MASK, .to_action = KC_GRAVE },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_SLASH },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_SLASH },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_GRAVE },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK|LEFT_SHIFT_MASK, .to_action = KC_GRAVE },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_GRAVE },
  // KC_RBRACKET  102  108
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK|LEFT_SHIFT_MASK, .to_action = KC_2 },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK|RIGHT_SHIFT_MASK, .to_action = KC_2 },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_6 },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_6 },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK|LEFT_SHIFT_MASK, .to_action = KC_2 },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_2 },
  // KC_A  108  114
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_A },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_A },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_A },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_A },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_A },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_A },
  // KC_S  114  120
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_O },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_O },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_O },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_O },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_O },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_O },
  // KC_D  120  126
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_E },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_E },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_E },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_E },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_E },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_E },
  // KC_F  126  133
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_U },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_U },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_U },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_U },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_EQUAL },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_U },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_U },
  // KC_G  133  139
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_I },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_I },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_I },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_I },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_I },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_I },
  // KC_H  139  147
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_D },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_D },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_D },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_D },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_7 },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_HOME },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_D },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_D },
  // KC_J  147  155
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_H },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_H },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_H },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_H },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_0 },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_LEFT },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_H },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_H },
  // KC_K  155  163
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_T },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_T },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_T },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_T },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_9 },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_DOWN },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_T },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_T },
  // KC_L  163  171
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_N },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_N },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_N },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_N },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_SLASH },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_RIGHT },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_N },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_N },
  // KC_SCLN  171  179
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_S },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_S },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_S },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_S },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_MINUS },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_END },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_S },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_S },
  // KC_QUOTE  179  186
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_MINUS },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_MINUS },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_2 },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_2 },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_4 },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_MINUS },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_MINUS },
  // KC_BSLS  186  187
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_TAB },
  // KC_Z  187  193
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_QUOTE },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_QUOTE },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_QUOTE },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_QUOTE },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_QUOTE },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_QUOTE },
  // KC_X  193  199
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_Q },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_Q },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_Q },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_Q },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_Q },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_Q },
  // KC_C  199  205
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_J },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_J },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_J },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_J },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_J },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_J },
  // KC_V  205  211
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_K },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_K },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_K },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_K },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_K },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_K },
  // KC_B  211  217
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_X },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_X },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_X },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_X },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_X },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_X },
  // KC_N  217  225
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_B },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_B },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_B },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_B },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_1 },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_CTRL_MASK, .to_action = KC_LEFT },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_B },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_B },
  // KC_M  225  233
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_M },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_M },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_M },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_M },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_EQUAL },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_PGDOWN },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_M },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_M },
  // KC_COMMA  233  241
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_W },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_W },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_W },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_W },
  { .from_modifiers = MOD4_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_3 },
  { .from_modifiers = MOD5_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_CTRL_MASK, .to_action = KC_RIGHT },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_W },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_W },
  // KC_DOT  241  247
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_V },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_V },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_V },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_V },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_V },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_V },
  // KC_SLASH  247  253
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_Z },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_Z },
  { .from_modifiers = MOD2_MASK, .from_absorbing_modifiers = MOD2_MASK, .to_modifiers = LEFT_SHIFT_MASK, .to_action = KC_Z },
  { .from_modifiers = MOD3_MASK, .from_absorbing_modifiers = MOD3_MASK, .to_modifiers = RIGHT_SHIFT_MASK, .to_action = KC_Z },
  { .from_modifiers = MOD1_MASK, .from_absorbing_modifiers = 0, .to_modifiers = LEFT_META_MASK, .to_action = KC_Z },
  { .from_modifiers = 0, .from_absorbing_modifiers = 0, .to_modifiers = 0, .to_action = KC_Z },
  // KC_SPACE  253  255
  { .from_modifiers = MOD4_MASK|MOD2_MASK, .from_absorbing_modifiers = 0, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_N },
  { .from_modifiers = MOD4_MASK|MOD3_MASK, .from_absorbing_modifiers = 0, .to_modifiers = RIGHT_ALT_MASK, .to_action = KC_N },
};


const __flash struct key_definition our_key_definitions[] = {
  [KC_TAB] = { modifier_key_style, .modifier_key = { MOD5_MASK, 0 } },
  [KC_GRAVE] = { modifier_key_style, .modifier_key = { MOD1_MASK, LEFT_META_MASK } },
  [KC_LSFT] = { modifier_key_style, .modifier_key = { MOD2_MASK, LEFT_SHIFT_MASK } },
  [KC_RSFT] = { modifier_key_style, .modifier_key = { MOD3_MASK, RIGHT_SHIFT_MASK } },
  [KC_CAPS] = { modifier_key_style, .modifier_key = { MOD4_MASK, 0 } },
  [KC_RALT] = { modifier_key_style, .modifier_key = { MOD4_MASK, RIGHT_ALT_MASK } },

  [KC_1] = { action_key_style, .action_key = { .mappings_start = 0, .mappings_end = 2 } },
  [KC_2] = { action_key_style, .action_key = { .mappings_start = 2, .mappings_end = 4 } },
  [KC_3] = { action_key_style, .action_key = { .mappings_start = 4, .mappings_end = 6 } },
  [KC_4] = { action_key_style, .action_key = { .mappings_start = 6, .mappings_end = 8 } },
  [KC_5] = { action_key_style, .action_key = { .mappings_start = 8, .mappings_end = 10 } },
  [KC_6] = { action_key_style, .action_key = { .mappings_start = 10, .mappings_end = 12 } },
  [KC_7] = { action_key_style, .action_key = { .mappings_start = 12, .mappings_end = 14 } },
  [KC_8] = { action_key_style, .action_key = { .mappings_start = 14, .mappings_end = 16 } },
  [KC_9] = { action_key_style, .action_key = { .mappings_start = 16, .mappings_end = 18 } },
  [KC_0] = { action_key_style, .action_key = { .mappings_start = 18, .mappings_end = 20 } },
  [KC_MINUS] = { action_key_style, .action_key = { .mappings_start = 20, .mappings_end = 22 } },
  [KC_EQUAL] = { action_key_style, .action_key = { .mappings_start = 22, .mappings_end = 24 } },
  [KC_Q] = { action_key_style, .action_key = { .mappings_start = 24, .mappings_end = 31 } },
  [KC_W] = { action_key_style, .action_key = { .mappings_start = 31, .mappings_end = 38 } },
  [KC_E] = { action_key_style, .action_key = { .mappings_start = 38, .mappings_end = 45 } },
  [KC_R] = { action_key_style, .action_key = { .mappings_start = 45, .mappings_end = 52 } },
  [KC_T] = { action_key_style, .action_key = { .mappings_start = 52, .mappings_end = 58 } },
  [KC_Y] = { action_key_style, .action_key = { .mappings_start = 58, .mappings_end = 65 } },
  [KC_U] = { action_key_style, .action_key = { .mappings_start = 65, .mappings_end = 73 } },
  [KC_I] = { action_key_style, .action_key = { .mappings_start = 73, .mappings_end = 81 } },
  [KC_O] = { action_key_style, .action_key = { .mappings_start = 81, .mappings_end = 88 } },
  [KC_P] = { action_key_style, .action_key = { .mappings_start = 88, .mappings_end = 95 } },
  [KC_LBRACKET] = { action_key_style, .action_key = { .mappings_start = 95, .mappings_end = 102 } },
  [KC_RBRACKET] = { action_key_style, .action_key = { .mappings_start = 102, .mappings_end = 108 } },
  [KC_A] = { action_key_style, .action_key = { .mappings_start = 108, .mappings_end = 114 } },
  [KC_S] = { action_key_style, .action_key = { .mappings_start = 114, .mappings_end = 120 } },
  [KC_D] = { action_key_style, .action_key = { .mappings_start = 120, .mappings_end = 126 } },
  [KC_F] = { action_key_style, .action_key = { .mappings_start = 126, .mappings_end = 133 } },
  [KC_G] = { action_key_style, .action_key = { .mappings_start = 133, .mappings_end = 139 } },
  [KC_H] = { action_key_style, .action_key = { .mappings_start = 139, .mappings_end = 147 } },
  [KC_J] = { action_key_style, .action_key = { .mappings_start = 147, .mappings_end = 155 } },
  [KC_K] = { action_key_style, .action_key = { .mappings_start = 155, .mappings_end = 163 } },
  [KC_L] = { action_key_style, .action_key = { .mappings_start = 163, .mappings_end = 171 } },
  [KC_SCLN] = { action_key_style, .action_key = { .mappings_start = 171, .mappings_end = 179 } },
  [KC_QUOTE] = { action_key_style, .action_key = { .mappings_start = 179, .mappings_end = 186 } },
  [KC_BSLS] = { action_key_style, .action_key = { .mappings_start = 186, .mappings_end = 187 } },
  [KC_Z] = { action_key_style, .action_key = { .mappings_start = 187, .mappings_end = 193 } },
  [KC_X] = { action_key_style, .action_key = { .mappings_start = 193, .mappings_end = 199 } },
  [KC_C] = { action_key_style, .action_key = { .mappings_start = 199, .mappings_end = 205 } },
  [KC_V] = { action_key_style, .action_key = { .mappings_start = 205, .mappings_end = 211 } },
  [KC_B] = { action_key_style, .action_key = { .mappings_start = 211, .mappings_end = 217 } },
  [KC_N] = { action_key_style, .action_key = { .mappings_start = 217, .mappings_end = 225 } },
  [KC_M] = { action_key_style, .action_key = { .mappings_start = 225, .mappings_end = 233 } },
  [KC_COMMA] = { action_key_style, .action_key = { .mappings_start = 233, .mappings_end = 241 } },
  [KC_DOT] = { action_key_style, .action_key = { .mappings_start = 241, .mappings_end = 247 } },
  [KC_SLASH] = { action_key_style, .action_key = { .mappings_start = 247, .mappings_end = 253 } },
  [KC_SPACE] = { action_key_style, .action_key = { .mappings_start = 253, .mappings_end = 255 } },
};

const uint8_t our_num_keys = (sizeof our_key_definitions)/(sizeof our_key_definitions[0]);
